### ISSUE TITLE
Tracking devkit PackageInfo mess fallout

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#100]
The dev-kit shipped with a broken PackageInfo a few days back, causing mods that were baked using it to include entire copies of vanilla species and spawn groups that they should not. This issue will simply track the status the involved mods so we can see when it's safe to go back to full data pushes.

Mods that have changed since the broken update, to verify:
- [x] 1373744537 - AC2
- [x] 1576299694 - Elemental Ark
- [x] 1675895024 - No Untameables (? not sure)
- [x] 1729386191 - AC: Bonus Content (BonusDinoMod)
- [x] 893735676 - Ark: Eternal

For each mod, we should wait for a re-bake on the fixed version of the dev-kit before pushing.

**Comment by coldino** [comment]
As of today:

* AC2 - fixed and clean
* Elemental Ark - fixed and clean
* No Untameables has some changes to spawn groups but even if they are related they are minor
* AC: Bonus has Skeletal species and Zombie as a result of them being removed from the base game, but this is legit

But:
* Ark: Eternal has many species added, starting from Rockwell. This is still a problem.

I'll do a custom run and push of all but Ark: Eternal.

**Comment by coldino** [comment]
Today's updates:

* 1125442531 - Gaia
* 1576299694 - Elemental Ark
* 1729386191 - ARK Additions: Brachiosaurus

All look clean. Pushing them, still avoiding AE.

**Comment by alex4401** [comment]
AE has been updated, and the data was pushed to Obelisk 7 hours ago by coldino.
