### ISSUE TITLE
Valguero Ice Wyvern removal

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#101]
Valguero Ice Wyvern is being replaced by the Ragnarok Ice Wyvern.

This is the first time a common tamable species has been removed from the game. If the ASB species data is allowed to go live, libraries containing this species will be broken.

Current thoughts on a plan:
* Delay the data release
* Add the ability to include species replacement data into Purlovia via overrides
* Add the Val Ice Wyvern -> Rag Ice Wyvern data to `overrides.yaml`
* Bump the `species.json` format version - **this will stop existing ASB clients loading the file**
* Extend ASB to read this remap data and apply the changes to libraries
* Allow ASB to accept the new format version
* Release ASB with these changes
* Release the species data

The releases must happen in this order to avoid a mess at the user's end.

@cadon can you comment on whether this sounds viable for ASB?

**Comment by coldino** [comment]
This also applies to Dire Polar Bears.

**Comment by cadon** [comment]
The needed changes in ASB are done:
* needed format version is set to `1.13`
* remapping dictionary is loaded and used

I'll release a new version (0.39.5) with these changes soon.

**Comment by alex4401** [comment]
ASB version 0.39.5.1 was released 18 days ago, and the issue seems gone on both sides.
