### ISSUE TITLE
Stop using version.txt

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#103]
The `version.txt` file is no longer being updated reliably on content changes.

Our current workaround for this reads the version of the running official servers and is not idea, but should take over as **the** method and reading `version.txt` should be disabled.

A better direction in future is to use alex's hook (in `utils/shootergameserver_fwrite_hook.c`) to get the version from a locally-started server instance.

**Comment by alex4401** [comment]
Closed with #deef2f51ac50d341b6d82e4c9a494025c627e496.
