### ISSUE TITLE
Unable to extract any data

### ISSUE THREAD

**Issue by cokll** [arkutils/Purlovia#140]
(Purlovia-yUlChiBb) D:\Purlovia>python -m automate --notify --skip-install --skip-commit --skip-pull --skip-push
STARTUP:root:
STARTUP:root:----------------------------------------------------------------------------------------------------
STARTUP:root:
INFO:automate.cli:DEV mode enabled
INFO:automate.run:Version: local development
INFO:automate.ark:Ensuring SteamCMD is installed
INFO:automate.ark:Ensuring Ark is installed and up to date
INFO:automate.ark:(skipped)
INFO:automate.ark:Attempting to collect Ark server version within Docker...
WARNING:automate.ark:Unable to run docker command
INFO:automate.ark:Game version from version.txt: 341.22
INFO:automate.ark:Game version from official servers API: 341.19
WARNING:automate.ark:Mismatched version from version.txt and official server API - choosing version.txt
INFO:automate.ark:Ensuring mods are installed and up to date
INFO:automate.ark:No mods to update
INFO:automate.ark:Removing steam workshop cache
INFO:automate.ark:(skipped)
INFO:ark.discovery:Beginning hierarchy discovery
INFO:ue.hierarchy:Loading internal UE hierarchy from: config\hierarchy.yaml
WARNING:ark.discovery:Could not place 688 entries from 155 parents (see livedata\hierarchy_skips.txt)
INFO:ark.discovery:Hierarchy reconstruction complete
INFO:automate.run:Automation completed

**Comment by coldino** [comment]
A bit of background is needed here. I see you have specified `--skip-install`, but have you run without that option before to actually install the game assets?

If this is your first time I would recommend significantly reducing the mod list in `config/config.ini` then running just one stage to test the process - e.g.:
```sh
python -m automate wiki.items
```

This should download the game assets and the mods you configured before creating output in `output\data\wiki`.

**Comment by cokll** [comment]
Purlovia-yUlChiBb) D:\Purlovia>python -m automate wiki.items
STARTUP:root:
STARTUP:root:----------------------------------------------------------------------------------------------------
STARTUP:root:
INFO:automate.cli:DEV mode enabled
INFO:automate.run:Version: local development
INFO:automate.ark:Ensuring SteamCMD is installed
INFO:automate.ark:Ensuring Ark is installed and up to date
INFO:automate.steamcmd:Installing game 376030 to D:\Purlovia\livedata\game
INFO:automate.steamcmd:SteamCMD process exited successfully with code 0 (0x0)
INFO:automate.ark:Attempting to collect Ark server version within Docker...
WARNING:automate.ark:Unable to run docker command
INFO:automate.ark:Game version from version.txt: 341.22
INFO:automate.ark:Game version from official servers API: 341.19
WARNING:automate.ark:Mismatched version from version.txt and official server API - choosing version.txt
INFO:automate.ark:Ensuring mods are installed and up to date
INFO:automate.ark:No mods to update
INFO:automate.ark:Removing steam workshop cache
INFO:ark.discovery:Beginning hierarchy discovery
INFO:ue.hierarchy:Loading internal UE hierarchy from: config\hierarchy.yaml
WARNING:ark.discovery:Could not place 688 entries from 155 parents (see livedata\hierarchy_skips.txt)
INFO:ark.discovery:Hierarchy reconstruction complete
INFO:automate.run:Automation completed


Same problem@coldino

**Comment by coldino** [comment]
Perhaps you can give us some background then.

* What changes have you made to config or anything else?
* Did you have any issues when the game data was installed first time?

**Comment by cokll** [comment]
> Perhaps you can give us some background then.
> 
> * What changes have you made to config or anything else?
> * Did you have any issues when the game data was installed first time?
This is not the first installation
I used it about six months ago

**Comment by cokll** [comment]
`# Global config
[settings]
DataDir=livedata # Base directory of runtime data (SteamCMD and the managed game install)
OutputPath=output # Base directory of the output directory/repository

SeparateOfficialMods= # Official mods that should not be included in the main export
    111111111
    CrystalIsles

[steamcmd]
RetryCount=5 # Number of times to retry failed attempts (because SteamCMD is awful)
UninstallUnusedMods=False # True/False to uninstall mods that are no longer in the [mods] section below

[git]
Branch=master # Branch to use when committing changes
UseReset=True # True to perform a hard reset, False to perform a pull
UseIdentity=False # True to require full git identity, False to skip the check and disable commit/push

[dev]
# empty placeholder

[errors]
SendNotifications=True # True to send notifications of errors, if specific methods are configured
MessageHeader=Purlovia ran into an error:
# Set env PURLOVIA_DISCORD_HOOK to the Discord webhook URL
# Set env PURLOVIA_DISCORD_ROLE to the numeric ID of a role to @ mention, if desired


# Config for each export subsystem
[export-defaults]
PrettyJson=True # True to prettify the exported json, False to compress it (may be overridden in each export section)

[export-asb]
PublishSubDir=data/asb # Sub-directory to publish values files to, within OutputPath
CommitHeader=Raptor Claus just dropped some files off for ASB

[export-wiki]
PublishSubDir=data/wiki # Sub-directory to publish values files to, within OutputPath
CommitHeader=Raptor Claus just dropped some files off for the Ark wiki

ExportVanillaMaps=True

[processing]
# empty placeholder

# List of mods that are part of vanilla Ark, in the form bp_tag=mod_id
[official-mods]
LostIsland=LostIsland
Ragnarok=Ragnarok
TheCenter=TheCenter
Valguero=Valguero
CrystalIsles=CrystalIsles
PrimitivePlus=111111111

# Combine mod outputs together
[combine-mods]
PrimitivePlusMod=PrimitivePlus
APS=PrimitivePlus

# Mod IDs to install, update, extract and publish [names are ignored and present to ease maintenance only]
[mods]
# Separated from base game install
111111111=PrimitivePlus
CrystalIsles=CrystalIsles


[mods-ignore]
# Large, for later consideration
916417001  = "Ebenus Astrum"                            # 3804 Mb,   39215 subs,   2880 faves
972887420  = "Jurassic Park Expansion"                  # 3271 Mb,   88030 subs,   6840 faves
538986229  = "Annunaki Genesis (v3.21.0)"               # 2035 Mb,  782519 subs,  33638 faves (old? 2017-10-12)

# Only contains 2 species
655581765  = "Pimp My Dino"                             #  401 Mb,  341998 subs,  10327 faves (old? 2016-03-31)

# Unable to process
632898827  = "Dino Colors Plus"                         #    2 Mb,  130242 subs,   2242 faves (old? 2017-05-11)
833379388  = "Pugnacia Dinos"                           # 2247 Mb,  120504 subs,   5695 faves
772181615  = "Total Conversion: Ark Remastered"         #   86 Mb,    9323 subs,   1251 faves (old? 2016-12-10)

# Officially released now - Conflicts with the official Mod Tag
804312798  = "Crystal Isles"

# Appear to be removed from Steam
1606708617=ARK: Mysterious Mysteries
1821112850=Iguana - Mysterious Mysteries
1268749723=Origin Manticore
1729512589=ARK Additions: Brachiosaurus!
1590726079=Auto-Harvest Ankylo
1768499278=Additional Creatures 2: JPE Rebalance

[optimisation]
SearchIgnore= # List of regexes used to filter out paths when searching for species
    /Game/Localization/.*                       # Contains only text
    /Game/PrimalEarth/Weapon[^/]+.*             # Tool models and rigging
    .*/ReflectionCaptures/.*                    # Large environment maps
    /Game/Maps/MainMenu                         # Main menu level
    /Game/Maps/ShooterEntry                     # ???
    /Game/Maps/PGARK                            # Procedural ARKs
    /Game/(Maps|Mods)/.*/.*BossArena.*          # Boss arenas
    /Game/Mods/Ragnarok/Ragnarok_Arena_01       # Ragnarok boss arena
    .*/([cC]ore)?([aA]nimation|[aA]nim|[eE]ffect|[mM]aterial|[mM]esh|MIC|[pP]article|[sS]ound|[tT]exture)s?/.*
    .*/Light(ing)?Probes/.*
    .*(?<!Spawners)(?<!Spawners/New)/T_[^/]+    # Texture assets, unless inside Spawners
    .*/(Meshes|TempMaterials|Landscape|[dD]roppedMeshes|[cC]lutter|BehaviorTrees|CoreAI)/.*
    .*/(AIController|PostEffects|PostProcess|AnimTexture|Icon|FX)/.*
    .*[_/](AI_Blueprint|AIController|Emitter|ProxyMesh|ChildIBL|MasterIBL)([_/].+|$)
    .*[_/](VFX|M[iI]|Mic|MIC|MAT|SK)([_/].+|$)
    .*[/](MM)([_/].+|$)
    .*/(Environment|Trees|Foliage)/.*_[sS]ettings
    .*/(Environment|Trees)/.*_[pP]ickup
    .*/(Environment|Trees)/.*_[mM]at(Inst)?
    .*/(Environment|Trees|Clutter)(/.*[_/]|/)(Tex|Landscape|Clutter|SM)([_/].+|$)
    .*/(Environment|Trees)/(Rocks|Sky)

`

**Comment by coldino** [comment]
Only changes I see there are removing the mods - this doesn't stop it running for me. Are you sure you don't have any code changes?

Also try this and report back to see the list of available extraction stages:
```
> python -m automate wiki.items --list-stages
Available stages:
  sanity
    sanity.species
    sanity.items
    sanity.maps
  asb
    asb.species
  wiki
    wiki.maps
    wiki.spawn_groups
    wiki.engrams
    wiki.items [*]
    wiki.drops
    wiki.loot_crates
    wiki.species
    wiki.missions
    wiki.event_colors
  maps
    maps.biome_maps
```

You might consider wiping the code and fetching a new copy. The game data can be kept.

**Comment by cokll** [comment]
> Only changes I see there are removing the mods - this doesn't stop it running for me. Are you sure you don't have any code changes?
> 
> Also try this and report back to see the list of available extraction stages:
> 
> ```
> > python -m automate wiki.items --list-stages
> Available stages:
>   sanity
>     sanity.species
>     sanity.items
>     sanity.maps
>   asb
>     asb.species
>   wiki
>     wiki.maps
>     wiki.spawn_groups
>     wiki.engrams
>     wiki.items [*]
>     wiki.drops
>     wiki.loot_crates
>     wiki.species
>     wiki.missions
>     wiki.event_colors
>   maps
>     maps.biome_maps
> ```
> 
> You might consider wiping the code and fetching a new copy. The game data can be kept.

<pre>

(Purlovia-yUlChiBb) D:\Purlovia>python -m automate wiki.items --list-stages
C:\Users\cokll\.virtualenvs\Purlovia-yUlChiBb\lib\site-packages\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (4.0.0) doesn't match a supported version!
  RequestsDependencyWarning)
Available stages:
  sanity
    sanity.species
    sanity.items
    sanity.maps
  asb
    asb.species
  wiki
    wiki.maps
    wiki.spawn_groups
    wiki.engrams
    wiki.items [*]
    wiki.drops
    wiki.loot_crates
    wiki.species
    wiki.missions
    wiki.event_colors
  maps
    maps.biome_maps

</pre>



Yes, the code has not changed

**Comment by coldino** [comment]
Pretty certain with this log output you must have code changes. If you just updated with Git it will have kept your old changes and integrated them with the new code. What does `git status` say?

**Comment by cokll** [comment]
The problem is found. It's Git problem

thank you
