### ISSUE TITLE
Ragnarok seems to have coding problems

### ISSUE THREAD

**Issue by cokll** [arkutils/Purlovia#141]
<pre>
STARTUP:root:
STARTUP:root:----------------------------------------------------------------------------------------------------
STARTUP:root:
INFO:automate.cli:DEV mode enabled
INFO:automate.run:Version: local development
INFO:automate.ark:Ensuring SteamCMD is installed
INFO:automate.ark:Ensuring Ark is installed and up to date
INFO:automate.ark:(skipped)
INFO:automate.ark:Attempting to collect Ark server version within Docker...
WARNING:automate.ark:Unable to run docker command
INFO:automate.ark:Game version from version.txt: 341.22
INFO:automate.ark:Game version from official servers API: 341.19
WARNING:automate.ark:Mismatched version from version.txt and official server API - choosing version.txt
INFO:automate.ark:Ensuring mods are installed and up to date
INFO:automate.ark:No mods to update
INFO:automate.ark:Removing steam workshop cache
INFO:automate.ark:(skipped)
INFO:ark.discovery:Beginning hierarchy discovery
INFO:ue.hierarchy:Loading internal UE hierarchy from: config\hierarchy.yaml
WARNING:ark.discovery:Could not place 688 entries from 155 parents (see livedata\hierarchy_skips.txt)
INFO:ark.discovery:Hierarchy reconstruction complete
INFO:automate.exporter:Export beginning
INFO:automate.exporter:Extracting Sanity:Species in core
INFO:automate.exporter:Extracting Sanity:Items in core
INFO:automate.exporter:Extracting Sanity:Maps in core
INFO:automate.exporter:Extracting ASB:Species in core
INFO:automate.jsonutils:Saving export to output\data\asb\values.json with version 341.22.7885939
INFO:automate.exporter:Extracting Wiki:Map in core
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Mods/Ragnarok
INFO:automate.jsonutils:Saving export to output\data\wiki\Ragnarok\world_settings.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Ragnarok\npc_spawns.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Ragnarok\biomes.json with version 341.22.7885939
ERROR:automate.run:Caught exception during automation run. Aborting.
Traceback (most recent call last):
  File "E:\GitHub\Purlovia\automate\run.py", line 95, in run
    exporter.perform()
  File "E:\GitHub\Purlovia\automate\exporter.py", line 104, in perform
    self._perform_export()
  File "E:\GitHub\Purlovia\automate\exporter.py", line 158, in _perform_export
    stage.extract_core(root_path)
  File "E:\GitHub\Purlovia\export\wiki\stage_maps.py", line 54, in extract_core
    self._extract_and_save(version, path, Path(directory_name), levels)
  File "E:\GitHub\Purlovia\export\wiki\stage_maps.py", line 137, in _extract_and_save
    save_json_if_changed(output, (base_path / output_path), pretty_json)
  File "E:\GitHub\Purlovia\automate\jsonutils.py", line 28, in save_json_if_changed
    save_as_json(values, fullpath, pretty=pretty)
  File "E:\GitHub\Purlovia\automate\jsonutils.py", line 191, in save_as_json
    f.write(json_string)
UnicodeEncodeError: 'gbk' codec can't encode character '\ufeff' in position 130464: illegal multibyte sequence
</pre>

<pre>

STARTUP:root:
STARTUP:root:----------------------------------------------------------------------------------------------------
STARTUP:root:
INFO:automate.cli:DEV mode enabled
INFO:automate.run:Version: local development
INFO:automate.ark:Ensuring SteamCMD is installed
INFO:automate.ark:Ensuring Ark is installed and up to date
INFO:automate.ark:(skipped)
INFO:automate.ark:Attempting to collect Ark server version within Docker...
WARNING:automate.ark:Unable to run docker command
INFO:automate.ark:Game version from version.txt: 341.22
INFO:automate.ark:Game version from official servers API: 341.19
WARNING:automate.ark:Mismatched version from version.txt and official server API - choosing version.txt
INFO:ark.discovery:Beginning hierarchy discovery
INFO:ue.hierarchy:Loading internal UE hierarchy from: config\hierarchy.yaml
WARNING:ark.discovery:Could not place 688 entries from 155 parents (see livedata\hierarchy_skips.txt)
INFO:ark.discovery:Hierarchy reconstruction complete
INFO:automate.exporter:Export beginning
INFO:automate.exporter:Extracting Sanity:Species in core
INFO:automate.exporter:Extracting Sanity:Items in core
INFO:automate.exporter:Extracting Sanity:Maps in core
INFO:automate.exporter:Extracting ASB:Species in core
INFO:automate.jsonutils:No changes to output\data\asb\values.json
INFO:automate.exporter:Extracting Wiki:Map in core
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Maps/Genesis
INFO:automate.jsonutils:Saving export to output\data\wiki\Genesis\world_settings.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Genesis\npc_spawns.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Genesis\biomes.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Genesis\actors.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Genesis\missions.json with version 341.22.7885939
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Maps/TheIslandSubMaps
INFO:automate.jsonutils:Saving export to output\data\wiki\TheIslandSubMaps\world_settings.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\TheIslandSubMaps\npc_spawns.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\TheIslandSubMaps\biomes.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\TheIslandSubMaps\loot_crates.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\TheIslandSubMaps\actors.json with version 341.22.7885939
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Mods/Valguero
INFO:automate.jsonutils:Saving export to output\data\wiki\Valguero\world_settings.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Valguero\radiation_zones.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Valguero\npc_spawns.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Valguero\biomes.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Valguero\loot_crates.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Valguero\actors.json with version 341.22.7885939
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Mods/TheCenter
INFO:automate.jsonutils:Saving export to output\data\wiki\TheCenter\world_settings.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\TheCenter\npc_spawns.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\TheCenter\biomes.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\TheCenter\loot_crates.json with version 341.22.7885939
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Maps/ScorchedEarth
INFO:automate.jsonutils:Saving export to output\data\wiki\ScorchedEarth\world_settings.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\ScorchedEarth\npc_spawns.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\ScorchedEarth\biomes.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\ScorchedEarth\loot_crates.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\ScorchedEarth\actors.json with version 341.22.7885939
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Maps/Extinction
INFO:automate.jsonutils:Saving export to output\data\wiki\Extinction\world_settings.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Extinction\npc_spawns.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Extinction\biomes.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Extinction\loot_crates.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Extinction\actors.json with version 341.22.7885939
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Maps/Genesis2
INFO:automate.jsonutils:Saving export to output\data\wiki\Genesis2\world_settings.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Genesis2\npc_spawns.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Genesis2\biomes.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Genesis2\actors.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Genesis2\missions.json with version 341.22.7885939
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Mods/Ragnarok
INFO:automate.jsonutils:No changes to output\data\wiki\Ragnarok\world_settings.json
INFO:automate.jsonutils:No changes to output\data\wiki\Ragnarok\npc_spawns.json
INFO:automate.jsonutils:Saving export to output\data\wiki\Ragnarok\biomes.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Ragnarok\loot_crates.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Ragnarok\actors.json with version 341.22.7885939
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Maps/Aberration
INFO:automate.jsonutils:Saving export to output\data\wiki\Aberration\world_settings.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Aberration\radiation_zones.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Aberration\npc_spawns.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Aberration\biomes.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Aberration\loot_crates.json with version 341.22.7885939
INFO:automate.jsonutils:Saving export to output\data\wiki\Aberration\actors.json with version 341.22.7885939
INFO:automate.exporter:Extracting Wiki:SpawnGroup in core
INFO:automate.jsonutils:No changes to output\data\wiki\spawn_groups.json
INFO:automate.exporter:Extracting Wiki:Engrams in core
INFO:automate.jsonutils:No changes to output\data\wiki\engrams.json
INFO:automate.exporter:Extracting Wiki:Items in core
INFO:automate.jsonutils:No changes to output\data\wiki\items.json
INFO:automate.exporter:Extracting Wiki:Drops in core
INFO:automate.jsonutils:No changes to output\data\wiki\drops.json
INFO:automate.exporter:Extracting Wiki:LootCrates in core
INFO:automate.jsonutils:No changes to output\data\wiki\loot_crates.json
INFO:automate.exporter:Extracting Wiki:Species in core
INFO:automate.jsonutils:No changes to output\data\wiki\species.json
INFO:automate.exporter:Extracting Wiki:Missions in core
INFO:automate.jsonutils:No changes to output\data\wiki\missions.json
INFO:automate.exporter:Extracting Wiki:EventColors in core
INFO:automate.jsonutils:No changes to output\data\wiki\event_colors.json
INFO:automate.exporter:Extracting WikiMaps:ProcessBiomeMaps in core
INFO:export.maps.stage_biome_maps:Processing data of map: Aberration
INFO:export.maps.stage_biome_maps:Processing data of map: Extinction
INFO:export.maps.stage_biome_maps:Processing data of map: Genesis
INFO:export.maps.stage_biome_maps:Processing data of map: Genesis2
INFO:export.maps.stage_biome_maps:Processing data of map: Ragnarok
ERROR:automate.run:Caught exception during automation run. Aborting.
Traceback (most recent call last):
  File "E:\GitHub\Purlovia\automate\run.py", line 95, in run
    exporter.perform()
  File "E:\GitHub\Purlovia\automate\exporter.py", line 104, in perform
    self._perform_export()
  File "E:\GitHub\Purlovia\automate\exporter.py", line 158, in _perform_export
    stage.extract_core(root_path)
  File "E:\GitHub\Purlovia\export\maps\stage_biome_maps.py", line 28, in extract_core
    self._process(self.wiki_path / data_path, self.output_path / data_path, None)
  File "E:\GitHub\Purlovia\export\maps\stage_biome_maps.py", line 49, in _process
    data_biomes = self.load_json_file(in_path / 'biomes.json')
  File "E:\GitHub\Purlovia\export\maps\stage_base.py", line 31, in load_json_file
    data = json.load(fp)
  File "C:\Python\Python37_64\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\cokll\.virtualenvs\Purlovia-9dt0qJC0\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 126552: invalid start byte

</pre>

**Comment by cokll** [comment]
modify automate\jsonutils.py

<pre>
 def save_as_json(data, filename, pretty=False):
    path = Path(filename).parent
    path.mkdir(parents=True, exist_ok=True)
    json_string = _format_json(data, pretty)
    with open(filename, 'w', newline='\n' , errors='ignore') as f:
        f.write(json_string)
</pre>
It's normal

But there seems to be no extraction  LostIsland

<pre>
STARTUP:root:
STARTUP:root:----------------------------------------------------------------------------------------------------
STARTUP:root:
INFO:automate.cli:DEV mode enabled
INFO:automate.run:Version: local development
INFO:automate.ark:Ensuring SteamCMD is installed
INFO:automate.ark:Ensuring Ark is installed and up to date
INFO:automate.ark:(skipped)
INFO:automate.ark:Attempting to collect Ark server version within Docker...
WARNING:automate.ark:Unable to run docker command
INFO:automate.ark:Game version from version.txt: 341.22
INFO:automate.ark:Game version from official servers API: 341.19
WARNING:automate.ark:Mismatched version from version.txt and official server API - choosing version.txt
INFO:ark.discovery:Beginning hierarchy discovery
INFO:ue.hierarchy:Loading internal UE hierarchy from: config\hierarchy.yaml
WARNING:ark.discovery:Could not place 688 entries from 155 parents (see livedata\hierarchy_skips.txt)
INFO:ark.discovery:Hierarchy reconstruction complete
INFO:automate.exporter:Export beginning
INFO:automate.exporter:Extracting Sanity:Species in core
INFO:automate.exporter:Extracting Sanity:Items in core
INFO:automate.exporter:Extracting Sanity:Maps in core
INFO:automate.exporter:Extracting ASB:Species in core
INFO:automate.jsonutils:No changes to output\data\asb\values.json
INFO:automate.exporter:Extracting Wiki:Map in core
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Maps/TheIslandSubMaps
INFO:automate.jsonutils:No changes to output\data\wiki\TheIslandSubMaps\world_settings.json
INFO:automate.jsonutils:No changes to output\data\wiki\TheIslandSubMaps\npc_spawns.json
INFO:automate.jsonutils:No changes to output\data\wiki\TheIslandSubMaps\biomes.json
INFO:automate.jsonutils:No changes to output\data\wiki\TheIslandSubMaps\loot_crates.json
INFO:automate.jsonutils:No changes to output\data\wiki\TheIslandSubMaps\actors.json
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Maps/Genesis2
INFO:automate.jsonutils:No changes to output\data\wiki\Genesis2\world_settings.json
INFO:automate.jsonutils:No changes to output\data\wiki\Genesis2\npc_spawns.json
INFO:automate.jsonutils:No changes to output\data\wiki\Genesis2\biomes.json
INFO:automate.jsonutils:No changes to output\data\wiki\Genesis2\actors.json
INFO:automate.jsonutils:No changes to output\data\wiki\Genesis2\missions.json
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Mods/Valguero
INFO:automate.jsonutils:No changes to output\data\wiki\Valguero\world_settings.json
INFO:automate.jsonutils:No changes to output\data\wiki\Valguero\radiation_zones.json
INFO:automate.jsonutils:No changes to output\data\wiki\Valguero\npc_spawns.json
INFO:automate.jsonutils:No changes to output\data\wiki\Valguero\biomes.json
INFO:automate.jsonutils:No changes to output\data\wiki\Valguero\loot_crates.json
INFO:automate.jsonutils:No changes to output\data\wiki\Valguero\actors.json
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Maps/Aberration
INFO:automate.jsonutils:No changes to output\data\wiki\Aberration\world_settings.json
INFO:automate.jsonutils:No changes to output\data\wiki\Aberration\radiation_zones.json
INFO:automate.jsonutils:No changes to output\data\wiki\Aberration\npc_spawns.json
INFO:automate.jsonutils:No changes to output\data\wiki\Aberration\biomes.json
INFO:automate.jsonutils:No changes to output\data\wiki\Aberration\loot_crates.json
INFO:automate.jsonutils:No changes to output\data\wiki\Aberration\actors.json
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Maps/Extinction
INFO:automate.jsonutils:No changes to output\data\wiki\Extinction\world_settings.json
INFO:automate.jsonutils:No changes to output\data\wiki\Extinction\npc_spawns.json
INFO:automate.jsonutils:No changes to output\data\wiki\Extinction\biomes.json
INFO:automate.jsonutils:No changes to output\data\wiki\Extinction\loot_crates.json
INFO:automate.jsonutils:No changes to output\data\wiki\Extinction\actors.json
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Maps/Genesis
INFO:automate.jsonutils:No changes to output\data\wiki\Genesis\world_settings.json
INFO:automate.jsonutils:No changes to output\data\wiki\Genesis\npc_spawns.json
INFO:automate.jsonutils:No changes to output\data\wiki\Genesis\biomes.json
INFO:automate.jsonutils:No changes to output\data\wiki\Genesis\actors.json
INFO:automate.jsonutils:No changes to output\data\wiki\Genesis\missions.json
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Mods/Ragnarok
INFO:automate.jsonutils:No changes to output\data\wiki\Ragnarok\world_settings.json
INFO:automate.jsonutils:No changes to output\data\wiki\Ragnarok\npc_spawns.json
INFO:automate.jsonutils:Saving export to output\data\wiki\Ragnarok\biomes.json with version 341.22.7885939.3
INFO:automate.jsonutils:No changes to output\data\wiki\Ragnarok\loot_crates.json
INFO:automate.jsonutils:No changes to output\data\wiki\Ragnarok\actors.json
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Maps/ScorchedEarth
INFO:automate.jsonutils:No changes to output\data\wiki\ScorchedEarth\world_settings.json
INFO:automate.jsonutils:No changes to output\data\wiki\ScorchedEarth\npc_spawns.json
INFO:automate.jsonutils:No changes to output\data\wiki\ScorchedEarth\biomes.json
INFO:automate.jsonutils:No changes to output\data\wiki\ScorchedEarth\loot_crates.json
INFO:automate.jsonutils:No changes to output\data\wiki\ScorchedEarth\actors.json
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Mods/TheCenter
INFO:automate.jsonutils:No changes to output\data\wiki\TheCenter\world_settings.json
INFO:automate.jsonutils:No changes to output\data\wiki\TheCenter\npc_spawns.json
INFO:automate.jsonutils:No changes to output\data\wiki\TheCenter\biomes.json
INFO:automate.jsonutils:No changes to output\data\wiki\TheCenter\loot_crates.json
INFO:automate.exporter:Extracting Wiki:SpawnGroup in core
INFO:automate.jsonutils:No changes to output\data\wiki\spawn_groups.json
INFO:automate.exporter:Extracting Wiki:Engrams in core
INFO:automate.jsonutils:No changes to output\data\wiki\engrams.json
INFO:automate.exporter:Extracting Wiki:Items in core
INFO:automate.jsonutils:No changes to output\data\wiki\items.json
INFO:automate.exporter:Extracting Wiki:Drops in core
INFO:automate.jsonutils:No changes to output\data\wiki\drops.json
INFO:automate.exporter:Extracting Wiki:LootCrates in core
INFO:automate.jsonutils:No changes to output\data\wiki\loot_crates.json
INFO:automate.exporter:Extracting Wiki:Species in core
INFO:automate.jsonutils:No changes to output\data\wiki\species.json
INFO:automate.exporter:Extracting Wiki:Missions in core
INFO:automate.jsonutils:No changes to output\data\wiki\missions.json
INFO:automate.exporter:Extracting Wiki:EventColors in core
INFO:automate.jsonutils:No changes to output\data\wiki\event_colors.json
INFO:automate.exporter:Extracting WikiMaps:ProcessBiomeMaps in core
INFO:export.maps.stage_biome_maps:Processing data of map: Aberration
INFO:export.maps.stage_biome_maps:Processing data of map: Extinction
INFO:export.maps.stage_biome_maps:Processing data of map: Genesis
INFO:export.maps.stage_biome_maps:Processing data of map: Genesis2
INFO:export.maps.stage_biome_maps:Processing data of map: Ragnarok
INFO:export.maps.stage_biome_maps:Processing data of map: ScorchedEarth
INFO:export.maps.stage_biome_maps:Processing data of map: TheCenter
INFO:export.maps.stage_biome_maps:Processing data of map: TheIslandSubMaps
INFO:export.maps.stage_biome_maps:Processing data of map: Valguero
INFO:automate.exporter:Extracting ASB:Species in mod 111111111 'PrimitivePlus'
INFO:automate.jsonutils:No changes to output\data\asb\111111111-PrimitivePlus.json
INFO:automate.exporter:Extracting Wiki:Engrams in mod 111111111 'PrimitivePlus'
INFO:automate.jsonutils:No changes to output\data\wiki\111111111-PrimitivePlus\engrams.json
INFO:automate.exporter:Extracting Wiki:Items in mod 111111111 'PrimitivePlus'
INFO:automate.jsonutils:No changes to output\data\wiki\111111111-PrimitivePlus\items.json
INFO:automate.exporter:Extracting Wiki:Drops in mod 111111111 'PrimitivePlus'
INFO:automate.exporter:Extracting Wiki:LootCrates in mod 111111111 'PrimitivePlus'
INFO:automate.exporter:Extracting Wiki:Species in mod 111111111 'PrimitivePlus'
INFO:automate.jsonutils:No changes to output\data\wiki\111111111-PrimitivePlus\species.json
INFO:automate.exporter:Extracting Wiki:Missions in mod 111111111 'PrimitivePlus'
INFO:automate.exporter:Extracting Wiki:EventColors in mod 111111111 'PrimitivePlus'
INFO:automate.exporter:Extracting ASB:Species in mod CrystalIsles 'CrystalIsles'
INFO:automate.jsonutils:No changes to output\data\asb\CrystalIsles-CrystalIsles.json
INFO:automate.exporter:Extracting Wiki:Map in mod CrystalIsles 'CrystalIsles'
INFO:export.wiki.stage_maps:Performing extraction from map: /Game/Mods/CrystalIsles
INFO:automate.jsonutils:No changes to output\data\wiki\CrystalIsles-CrystalIsles\CrystalIsles\world_settings.json
INFO:automate.jsonutils:No changes to output\data\wiki\CrystalIsles-CrystalIsles\CrystalIsles\npc_spawns.json
INFO:automate.jsonutils:No changes to output\data\wiki\CrystalIsles-CrystalIsles\CrystalIsles\biomes.json
INFO:automate.jsonutils:No changes to output\data\wiki\CrystalIsles-CrystalIsles\CrystalIsles\loot_crates.json
INFO:automate.jsonutils:No changes to output\data\wiki\CrystalIsles-CrystalIsles\CrystalIsles\actors.json
INFO:automate.exporter:Extracting Wiki:SpawnGroup in mod CrystalIsles 'CrystalIsles'
INFO:automate.jsonutils:No changes to output\data\wiki\CrystalIsles-CrystalIsles\spawn_groups.json
INFO:automate.exporter:Extracting Wiki:Engrams in mod CrystalIsles 'CrystalIsles'
INFO:automate.exporter:Extracting Wiki:Items in mod CrystalIsles 'CrystalIsles'
INFO:automate.jsonutils:No changes to output\data\wiki\CrystalIsles-CrystalIsles\items.json
INFO:automate.exporter:Extracting Wiki:Drops in mod CrystalIsles 'CrystalIsles'
INFO:automate.jsonutils:No changes to output\data\wiki\CrystalIsles-CrystalIsles\drops.json
INFO:automate.exporter:Extracting Wiki:LootCrates in mod CrystalIsles 'CrystalIsles'
INFO:automate.exporter:Extracting Wiki:Species in mod CrystalIsles 'CrystalIsles'
INFO:automate.jsonutils:No changes to output\data\wiki\CrystalIsles-CrystalIsles\species.json
INFO:automate.exporter:Extracting Wiki:Missions in mod CrystalIsles 'CrystalIsles'
INFO:automate.exporter:Extracting Wiki:EventColors in mod CrystalIsles 'CrystalIsles'
INFO:automate.exporter:Finishing up Sanity root
INFO:automate.manifest:Updating manifest file
INFO:automate.manifest:No files present - removing existing manifest
INFO:automate.exporter:Finishing up ASB root
INFO:automate.manifest:Updating manifest file
INFO:automate.exporter:Finishing up Wiki root
INFO:automate.manifest:Updating manifest file
INFO:automate.exporter:Finishing up WikiMaps root
INFO:automate.manifest:Updating manifest file
INFO:automate.manifest:No files present - removing existing manifest
INFO:automate.run:Automation completed
</pre>

**Comment by coldino** [comment]
The Lost Island problem was likely caused by your Git issue, as the game data was fetched before the config change necessary to support it. To overcome this you need to remove the asset hierarchy cache. Add `--remove-cache` to your command once to force this to happen. It'll take a few minutes to rescan the assets, accelerating it for future runs.

**Comment by coldino** [comment]
Could try your encoding issues again after pulling master? 77d84c152043b86818efa2488eeb7d80bc98d5a8 attempts to make every texture file access in the system correctly handle UTF-8.

Using `errors='ignore'` is not something I would recommend or accept - it just hides a problem elsewhere.
