### ISSUE TITLE
Species GUIDs are not unique

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#29]

**Comment by VolatilePulse** [comment]
Partially addressed with 083531f3d4eef3b7d1ddae1c084da6e5e1f11057

There are still some issues including looking up the asset's export. Some of the Ark Eternal species have an _2 at the end of it's asset name but the export's name omits the _2.

There are also duplication across mods using the same species, but this is more likely and issue with how the DevKit handles "duplicating" assets for use in a mod. Notably, the glowpets in vanilla also share the same GUID with the exception of 1. Have not been able to identify the exact cause of this though.

Proposal for the SaveGameToolkit support would be if the save game contains the blueprint, use that as priority, even though it hasn't quite been seen yet. If the blueprint is missing, a combination of the species class and the UUID should be sufficient. However, this shouldn't be replied upon as we're still unsure of how the game knows the blueprint to load a species from.

**Comment by coldino** [comment]
Looked into this quite deeply now. It's apparent that this `UniqueGuidId` that appears in savegames is useless to us. When the Ark devs made new species they seem to have copy/pasted old ones and in most cases the GUID was not replaced.

Propose we remove the new "guid" field from the export entirely. We'll have to find a different way, or simply fall back in (clearly overlapping) class names within ASB.

**Comment by coldino** [comment]
For now, these are completely removed. See 9081ca9e002444158a9f83f69ffabdd56c16a5e5.
