### ISSUE TITLE
Extract bone damage multipliers

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#36]
For each species we need to extract the damage multipliers for each bone section.

1) Find the relevant properties
1) Agree an output format and what to include with @cadon 
   1) Do you include all or just bones that aren't 1?
1) Add extraction

**Comment by coldino** [comment]
Looks like a real simple case of exporting each member of a species' `BoneDamageAdjusters` array, where the multiplier != 1.

```py
>>> asset = loader['Game/PrimalEarth/Dinos/Trike/Trike_Character_BP']
>>> asset.default_export.properties.get_property('BoneDamageAdjusters')
ArrayProperty(count=2,
    0x0000 (0   ): StructProperty('BoneName = (NameProperty) c_head', 'DamageMultiplier = (FloatProperty) 0.15 (inexact)'),
    0x0001 (1   ): StructProperty('BoneName = (NameProperty) c_jaw', 'DamageMultiplier = (FloatProperty) 0.15 (inexact)'))
```

```py
>>> asset = loader['Game/PrimalEarth/Dinos/Turtle/Turtle_Character_BP']
>>> asset.default_export.properties.get_property('BoneDamageAdjusters')
ArrayProperty(count=5,
    0x0000 (0   ): StructProperty('BoneName = (NameProperty) c_neck5', 'DamageMultiplier = (FloatProperty) 1.0'),
    0x0001 (1   ): StructProperty('BoneName = (NameProperty) c_body', 'DamageMultiplier = (FloatProperty) 0.2 (inexact)'),
    0x0002 (2   ): StructProperty('BoneName = (NameProperty) c_tail1', 'DamageMultiplier = (FloatProperty) 0.5'),
    0x0003 (3   ): StructProperty('BoneName = (NameProperty) c_tail2', 'DamageMultiplier = (FloatProperty) 0.5'),
    0x0004 (4   ): StructProperty('BoneName = (NameProperty) c_tail3', 'DamageMultiplier = (FloatProperty) 0.5'))
```

**Comment by coldino** [comment]
Note that there's no common naming convention for the "body" bone (despite the two above examples). ASB's current assumption that the body bone is 1 will also have to change. @cadon

**Comment by cadon** [comment]
Currently ASB displays bone-damage-multipliers (BDMs) when they are listed in qowyn's data (q-data), e.g. the BDM of the neck for the carbonemys is listed as well, despite being 1; that's an important info as other body parts of this species are armored heavily. I'm not sure which BDM are listed in the q-data, maybe it's just all of them.

ASB simplifies the info by only using BDMs that contain specific words like `tail` in the description and also ignores any further entry with that word, e.g. `c_tail1` is displayed, all other entries that contain `tail` will be ignored; not sure if there are cases where that would matter. `jaw`-entries are not considered, last time I checked all species had the same multiplier for jaw and head anyway.

**Comment by coldino** [comment]
So it would be okay to send you all of the listed values, like in the listed cases above?

**Comment by cadon** [comment]
The current format for ASB is like
```
"boneDamageAdjusters": [
        {
          "Key": 0.5,
          "Value": "Tail"
        },
        {
          "Key": 3,
          "Value": "Head, Neck"
        }
      ]
```
i.e. a dictionary with the multipliers as the key and a csv-list for the according body-parts. Combining all similar body-parts (e.g. `tail1` and `tail2`) that have the same multiplier would be useful as well.

**Comment by coldino** [comment]
We agreed on the following format, with no naming translation in Purlovia:
```json
"boneDamageAdjusters": {
    "c_head": 0.15,
    "c_neck": 0.15
}
```
