### ISSUE TITLE
Reduce memory usage

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#37]
File data is kept in memory after the asset deserialisation process, giving access to the raw bytes that are related to each node in the tree. This was very helpful during prototyping and development of the system, but is a significant burden when thousands of assets need to be loaded for extraction. Current full run is ~10GB.

By far the most significant priority is to release the `MemoryStream`, its associated `memoryview` and underlying raw `bytes` from each asset - including every node in its tree.

Later, a method for releasing specific assets from the loader cache will also be needed, for example to release a mod's assets after its extraction is completed. Vanilla species should not be removed as they are frequently referenced by mods.

**Comment by coldino** [comment]
Implemented the lower-priority option of removing mod-related asset from the loader cache after export is complete in eefe635b571fbc532167bea5fcd597254f33baae.

**Comment by dustinpianalto** [comment]
After some testing it appears that the MemoryStream is not contributing to the memory issue. I replaced the hard reference to stream with a weakref proxy then verified that the only hard reference to stream is in the `_load_asset` method. I also verified that the stream object is getting garbage collected at the end of said method and show that the memory usage for the process remains the same.
```py
    def _load_asset(self, assetname: str, doNotLink=False):
        process = psutil.Process(os.getpid())
        mem = self._load_raw_asset(assetname)
        stream = MemoryStream(mem, 0, len(mem))
        asset = UAsset(weakref.proxy(stream))
        weakref.finalize(stream, finalizer_test)
        print(f'{"during: ":<23}{process.memory_info().rss}')
        print('ref count: ', sys.getrefcount(stream) - 1)
        asset.loader = self
        asset.assetname = assetname
        asset.name = assetname.split('/')[-1]
        asset.deserialise()
        print('post deserialization: ', process.memory_info().rss)
        print('ref count: ', sys.getrefcount(stream) - 1)
        if doNotLink:
            return asset
        asset.link()
        print(f'{"post linking: ":<23}{process.memory_info().rss}')
        exports = list(findComponentExports(asset))
        if len(exports) > 1:
            import warnings
            warnings.warn(f'Found more than one component in {assetname}!')
        asset.default_export = exports[0] if exports else None
        if asset.default_export:
            asset.default_class = asset.default_export.klass.value
        # self.cache[assetname] = asset
        print('ref count: ', sys.getrefcount(stream) - 1)
        print('weakref count: ', weakref.getweakrefcount(stream))
        print(asset.stream)
        return asset


def finalizer_test():
    print('stream has been garbage collected...')
```

Here is the script I used for testing

```py
from automate.ark import ArkSteamManager
import os
import psutil
import time
assetname = '/Game/PrimalEarth/Dinos/Raptor/Uberraptor/Deinonychus_Character_BP'
process = psutil.Process(os.getpid())
arkman = ArkSteamManager()
loader = arkman.createLoader()
print(f'{"before: ":<23}{process.memory_info().rss}')
asset = loader[assetname]
try:
    print(asset.stream)
except ReferenceError as e:
    print(e)
print(f'{"after: ":<23}{process.memory_info().rss}')
```

```
before:                47906816
during:                48353280
ref count:  1
post deserialization:  68595712
ref count:  1
post linking:          74641408
ref count:  1
weakref count:  2
<ue.stream.MemoryStream object at 0x7f787bacba90>
stream has been garbage collected...
weakly-referenced object no longer exists
after:                 74641408
```

**Comment by dustinpianalto** [comment]
On further exam it appears that every time certain methods such as `_parse_table` are called a new MemoryStream object is created instead of just referencing the main stream.

**Comment by dustinpianalto** [comment]
By making the stream passed in `deserialise_properties` a weakref it appears to reduce the memory consumption by ~300KB which is about 3/5ths of the size of the original stream. 
```
before:                47906816
during:                48345088
ref count:  1
post deserialization:  68603904
ref count:  1
post linking:          74272768
ref count:  1
weakref count:  2
<ue.stream.MemoryStream object at 0x7f463b9f3860>
stream has been garbage collected...
weakly-referenced object no longer exists
after:                 74272768
```

Commit 2a132644

**Comment by coldino** [comment]
Indeed these two fixes together do a really good job of reducing the peak memory usage.

Peak usage is down from nearly 10Gb to 5.5Gb and you can clearly see memory falling back to a baseline after each mod, meaning we can now scale without issue.
