### ISSUE TITLE
Implement colour region name lookups

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#39]

**Comment by cadon** [comment]
List with species color region names that have non-representing names in ARK and should be replaced while creating the values-file.
[species-color-region-names.json.txt](https://github.com/arkutils/Purlovia/files/3408366/species-color-region-names.json.txt)

**Comment by coldino** [comment]
Completed in bc7cf2405005e520eb0f5da5cb5e9636045b7b24.

**Comment by coldino** [comment]
Whoops. Species names -> BP conversion picked the wrong variant in some cases.

Fixed in 2666e7f3c1e2e090d4536bd171d68f7257852d87 and 3d9f9e9208becb42064a785ab265f79e6a374812.
