### ISSUE TITLE
Kraken's Better Dinos ini config not supported

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#45]
Config options such as `AllowFlyerSpeed` can not be supported.

**Comment by cadon** [comment]
It looks like this ini-parameter will convert the flyers to new flyer-species that can level their speed, so supporting this parameter should be the same as supporting other mod species.
See the [mod-page](https://steamcommunity.com/sharedfiles/filedetails/?id=1565015734) and search for `AllowFlyerSpeed`.

**Comment by coldino** [comment]
Great!  That's what I get for skimming and assuming.
