### ISSUE TITLE
Add `FileNotFoundError` exception handling for loading assets

### ISSUE THREAD

**Issue by VolatilePulse** [arkutils/Purlovia#48]
Some assets reference other assets that may have existed at one time or another but have since been removed. The loader throws a `FileNotFoundError` exception when it can not load a file and instead of completely discarding that asset, if possible, the script should elegantly discard the exception and continue gathering export information.

**Comment by coldino** [comment]
Fixed in bd7e0a6876d0f57ef558df3b9f2830e24acf5a72.
