### ISSUE TITLE
Use graph-based discovery to test name-based discovery

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#5]

**Comment by VolatilePulse** [comment]
While it is understood this would take a lot of resources and time to run against vanilla and larger mods, it should be done at some point to verify no assets have been missed based on the name based discovery system.

**Comment by coldino** [comment]
Absolutely. Need to verify that there are no species accepted by `ByInheritance.is_species` that are not accepted by `ByRawData.is_species`, using `loader.find_assetnames` to list every installed asset.
