### ISSUE TITLE
Add Ark DCSC gathering using new inheritance system

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#63]
New global inheritance system is in place and working. Using this, replace the Ark-specific property gathering systems.

Specifically this means adding a system to read and combine DCSCs from different places in the hierarchy, respecting components priorities where present.

Depends on #54, taking over one of its sub-tasks.

**Comment by alex4401** [comment]
This can be considered done since e6eab7ba58090b9607d7dc8d20e28ef25400e370.
