### ISSUE TITLE
Incorrect handling of DCSC Priorities

### ISSUE THREAD

**Issue by VolatilePulse** [arkutils/Purlovia#67]
Species' DCSC's are being ignored by Purlovia even though they have a higher DCSC priority. Both species have a priority of 5 where the other DCSC's do not have a priority. This apparently leads to the DCSC being ignored when it definitely shouldn't be.

[Primal Fear: Fabled Gacha](https://github.com/arkutils/Purlovia/files/3601932/DinoExport_10371141313793307.ini.txt)

[Primal Fear: Apex Velonasaur](https://github.com/arkutils/Purlovia/files/3601933/DinoExport_93824829294857285.ini.txt)

**Comment by coldino** [comment]
Still looking... Just a bit of data for now.

Fabled Gacha:
```
Applying ordered DCSCs:
DCSC pri=0 /Game/Mods/Primal_Fear/Dinos/Fabled/Fabled_Gacha/FabledGacha_Character_BP_Child.DinoCharacterStatusComponent_BP_FabledGacha_C_1
DCSC pri=0 /Game/Extinction/Dinos/Gacha/Gacha_Character_BP.DinoCharacterStatusComponent_BP_Gacha_C_1
```

Apex Velonasaur:
```
Applying ordered DCSCs:
DCSC pri=0 /Game/Mods/Primal_Fear/Dinos/Apex/Apex_Spindles/ApexSpindles_Character_BP_Child.DinoCharacterStatusComponent_BP_ApexSpindles_C_1
DCSC pri=0 /Game/Extinction/Dinos/Spindles/Spindles_Character_BP.DinoCharacterStatusComponent_BP_Spindles_C_1
```

Pretty sure we're missing a priority somewhere.

**Comment by coldino** [comment]
This should be fixed now. The mod data files will update in the next automated run, in a few hours.
